// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcoavrncoyiwwsozobbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjb2F2cm5jb3lpd3dzb3pvYmJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODcxOTcsImV4cCI6MjA3MzM2MzE5N30.cKkDS8XN_Fl68tATXxm83gDo7GzzWzR56lWQZpC86nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});